# Configuration for the primary display
[HDMI-A-1]
# make sure you place a tab for each file/directory
files =
			# entropy
			fill:IMAGE_FULL_PATH
			# OR entire directory
			fill:IMAGES_DIRECTORY_FULL_PATH
			# upper portion
			fill_low:IMAGE_FULL_PATH
			# center portion
			fill_center:IMAGE_FULL_PATH
			# lower portion
			fill_high:IMAGE_FULL_PATH
			# portion with face/s
			fill_attention:IMAGE_FULL_PATH
			fill_entropy:IMAGE_FULL_PATH
			stretch:IMAGE_FULL_PATH
			fit:IMAGE_FULL_PATH

# timeout before image switch [0 = no switch]
timeout = 15
# smooth frosted glass transition [default: false]
transition = true
# control the speed of transition [NOOP when transition=false]
transition_duration = 8
# random order [default: false]
randomize = true
# respect gamemode (disable cycling until game session is off) [default: true]
gamemode = true

# Configuration for a secondary display
[DP-1]
files =
			# entropy
			fill:IMAGE_FULL_PATH
			# OR entire directory
			fill:IMAGES_DIRECTORY_FULL_PATH
			# upper portion
			fill_low:IMAGE_FULL_PATH
			# center portion
			fill_center:IMAGE_FULL_PATH
			# lower portion
			fill_high:IMAGE_FULL_PATH
			# portion with face/s
			fill_attention:IMAGE_FULL_PATH
			fill_entropy:IMAGE_FULL_PATH
			stretch:IMAGE_FULL_PATH
			fit:IMAGE_FULL_PATH

timeout = 60
transition = true
randomize = true
transition_duration = 10
