#ifndef WALLE_LIQUID_GLASS_MATERIALIZE_H
#define WALLE_LIQUID_GLASS_MATERIALIZE_H

#include <stdbool.h>
#include <stdint.h>

enum walle_lg_material {
    WALLE_LG_MATERIAL_CLEAR,
    WALLE_LG_MATERIAL_REGULAR,
};

enum walle_lg_appearance {
    WALLE_LG_APPEARANCE_LIGHT,
    WALLE_LG_APPEARANCE_DARK,
};

enum walle_lg_numeric_field {
    WALLE_LG_INPUT_BLEED_AMOUNT,
    WALLE_LG_INPUT_BLEED_BLUR_RADIUS,
    WALLE_LG_INPUT_BLEED_COLOR_MATRIX_BLACK,
    WALLE_LG_INPUT_BLEED_COLOR_MATRIX_SATURATION,
    WALLE_LG_INPUT_BLEED_COLOR_MATRIX_WHITE,
    WALLE_LG_INPUT_BLEED_DISTANCE_0,
    WALLE_LG_INPUT_BLEED_DISTANCE_1,
    WALLE_LG_INPUT_BLEED_HEIGHT,
    WALLE_LG_INPUT_BLEED_OPACITY,
    WALLE_LG_INPUT_BLUR_DISTANCE_0,
    WALLE_LG_INPUT_BLUR_DISTANCE_1,
    WALLE_LG_INPUT_BLUR_DISTANCE_2,
    WALLE_LG_INPUT_BLUR_DISTANCE_3,
    WALLE_LG_INPUT_BLUR_DISTANCE_4,
    WALLE_LG_INPUT_BLUR_OPACITY_0,
    WALLE_LG_INPUT_BLUR_OPACITY_1,
    WALLE_LG_INPUT_BLUR_OPACITY_2,
    WALLE_LG_INPUT_BLUR_OPACITY_3,
    WALLE_LG_INPUT_BLUR_OPACITY_4,
    WALLE_LG_INPUT_BLUR_RADIUS,
    WALLE_LG_INPUT_CLAMP,
    WALLE_LG_INPUT_FACE_COLOR_MATRIX_BLACK,
    WALLE_LG_INPUT_FACE_COLOR_MATRIX_SATURATION,
    WALLE_LG_INPUT_FACE_COLOR_MATRIX_WHITE,
    WALLE_LG_INPUT_FACE_OPACITY,
    WALLE_LG_INPUT_INNER_REFRACTION_AMOUNT,
    WALLE_LG_INPUT_INNER_REFRACTION_HEIGHT,
    WALLE_LG_INPUT_MAX_HEADROOM,
    WALLE_LG_INPUT_OUTER_REFRACTION_AMOUNT,
    WALLE_LG_INPUT_OUTER_REFRACTION_HEIGHT,
    WALLE_LG_INPUT_REFRACTION_DISTANCE_0,
    WALLE_LG_INPUT_REFRACTION_DISTANCE_1,
    WALLE_LG_INPUT_REFRACTION_OPACITY,
    WALLE_LG_INPUT_SDR_GRADIENT_DISTANCE_0,
    WALLE_LG_INPUT_SDR_GRADIENT_DISTANCE_1,
    WALLE_LG_INPUT_SDR_HOLDING_TONE_WHITE,
    WALLE_LG_INPUT_SDR_SHADOW_OPACITY,
    WALLE_LG_INPUT_SHADOW_AMOUNT,
    WALLE_LG_INPUT_SHADOW_BLUR_RADIUS,
    WALLE_LG_INPUT_SHADOW_COLOR_MATRIX_BLACK,
    WALLE_LG_INPUT_SHADOW_COLOR_MATRIX_SATURATION,
    WALLE_LG_INPUT_SHADOW_COLOR_MATRIX_WHITE,
    WALLE_LG_INPUT_SHADOW_DISTANCE_OFFSET,
    WALLE_LG_INPUT_SHADOW_HEIGHT,
    WALLE_LG_INPUT_SHADOW_OPACITY,
    WALLE_LG_INPUT_SHADOW_RADIUS,
    WALLE_LG_INPUT_SHADOW_VIBRANCY_CONTRIBUTION,
    WALLE_LG_NUMERIC_FIELD_COUNT,
};

struct walle_lg_transition_request {
    enum walle_lg_material material;
    enum walle_lg_appearance appearance;
    uint32_t diameter;
    /* Apple's exact binary32 inputFaceOpacity/remaining value. */
    float visible_fraction;
};

struct walle_lg_numeric_inputs {
    float value[WALLE_LG_NUMERIC_FIELD_COUNT];
};

[[nodiscard]] bool walle_lg_transition_numeric_inputs(
    const struct walle_lg_transition_request *request,
    struct walle_lg_numeric_inputs *result
);

#endif
