#!/usr/bin/env python3
"""Emit the measured Liquid Glass material and tint laws as a Slang include.

Generated rather than hand-copied so the shader and the measurement cannot
drift: re-run the two derivations, re-run this, and the shader carries exactly
what was fitted.  Nothing here is tuned by eye.

Sources:
  analysis/derive_material_matrices.py  - the untinted colour transfer
  analysis/derive_tint_law.py           - `.tint()`, both variants
"""

import argparse
import json
from pathlib import Path

BANNER = """// GENERATED by analysis/generate_material_law_header.py - do not edit.
//
// Apple's Liquid Glass material, measured on macOS 26.6.1 (25G76).
//
// UNTINTED.  An affine 3x3 on the blurred backdrop.  `clear` works in sRGB CODE
// space - its gray ladder is a straight line there to 0.27 code values - while
// `regular` does not: its gray response bows above the chord by up to 4.4 code
// values at mid-scale, in both appearances, which no affine map in sRGB can
// produce.  It is affine in x**0.795, and ONE exponent covers both appearances.
// What produces that exponent is not known; it is not linear light, not the
// display's transfer, and not the capture path, which round-trips flat grays
// exactly.  It is carried as a measured constant rather than left as four code
// values of systematic error.
//
// TINTED.  The tint composites over the material's OWN OUTPUT, not over the raw
// backdrop, and separates into luminance and chroma:
//
//     out = base(tint) + beta(tint) * lumaOf(substrate)
//                      + gamma(tint) * chromaOf(substrate)
//
// gamma is measured as either one or zero and nothing between - even a tint
// 0.645 code values off the gray axis already blocks the backdrop's colour
// completely, and only an EXACTLY gray one lets it through.  That is a colour
// SPACE distinction, not a threshold: an exactly gray sRGB colour resolves to a
// grayscale space and takes the other path.
"""


def vector(values, width) -> str:
    return f"float{width}(" + ", ".join(f"{v: .8f}" for v in values[:width]) + ")"


def emit_material(records) -> list[str]:
    lines = ["struct WalleMaterialTransfer\n{",
             "    float3 fromR;",
             "    float3 fromG;",
             "    float3 fromB;",
             "    float3 offset;",
             "    float exponent;",
             "};\n"]
    for record in records:
        name = (f"kMaterial{record['variant'].capitalize()}"
                f"{record['appearance'].capitalize()}")
        lines.append(f"// {record['variant']} / {record['appearance']}: "
                     f"{record['backgroundCount']} unclipped backgrounds, "
                     f"{record['rootMeanSquareResidualCodes']} rms / "
                     f"{record['maximumResidualCodes']} max code values.")
        lines.append(f"static const WalleMaterialTransfer {name} = {{")
        for key in ("fromR", "fromG", "fromB"):
            lines.append(f"    {vector(record[key], 3)},")
        lines.append(f"    {vector([v / 1.0 for v in record['offsetCodes']], 3)},")
        lines.append(f"    {record['exponent']:.6f},")
        lines.append("};\n")
    return lines


def emit_tint(report) -> list[str]:
    lines = ["// Basis, chromatic: [r, g, b, 1, rr, gg, bb, rg, rb, gb], the tint",
             "// in 0..1.  Neutral: [level, level*level, 1], the tint's single",
             "// level in 0..1.  Each channel's ten (or three) base coefficients",
             "// are followed by its beta coefficients.",
             "struct WalleTintRegime\n{",
             "    float chromaticBase[30];",
             "    float chromaticBeta[30];",
             "    float neutralBase[9];",
             "    float neutralBeta[9];",
             "};\n"]
    for variant, appearances in sorted(report["variants"].items()):
        for appearance, entry in sorted(appearances.items()):
            regimes = entry.get("regimes", {})
            chromatic = regimes.get("chromatic")
            neutral = regimes.get("neutral")
            if chromatic is None:
                continue
            name = f"kTint{variant.capitalize()}{appearance.capitalize()}"
            lines.append(
                f"// {variant} / {appearance}: {chromatic['tintCount']} chromatic"
                + (f", {neutral['tintCount']} neutral" if neutral else
                   ", NEUTRAL NOT CAPTURED - the chromatic law stands in")
                + f"; fit {entry['rootMeanSquareResidualCodes']} rms /"
                f" {entry['maximumResidualCodes']} max code values.")
            lines.append(f"static const WalleTintRegime {name} = {{")
            for width, source, span in ((10, chromatic, slice(0, 10)),
                                        (10, chromatic, slice(10, 20)),
                                        (3, neutral, slice(0, 3)),
                                        (3, neutral, slice(3, 6))):
                lines.append("    {")
                for channel in range(3):
                    if source is None:
                        lines.append("        " + ", ".join(["0.0"] * width) + ",")
                        continue
                    row = source["coefficients"][channel][span]
                    lines.append("        "
                                 + ", ".join(f"{v: .8f}" for v in row) + ",")
                lines.append("    },")
            lines.append("};\n")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--material", type=Path, required=True)
    parser.add_argument("--tint", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    arguments = parser.parse_args()

    material = json.loads(arguments.material.read_text(encoding="utf-8"))
    tint = json.loads(arguments.tint.read_text(encoding="utf-8"))
    lines = [BANNER, *emit_material(material["records"]), *emit_tint(tint)]
    arguments.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {arguments.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
