#!/usr/bin/env python3
"""Emit the measured Liquid Glass material and tint laws as a Slang include.

Generated rather than hand-copied so the shader and the measurement cannot
drift: re-run the two derivations, re-run this, and the shader carries exactly
what was fitted.  Nothing here is tuned by eye.

Both laws are trivariate polynomials whose ORDER is chosen per material by
cross-validation, and the four materials do not agree on it.  Rather than emit
four shapes, this pads every one out to the widest order any of them chose:
the basis is ordered by total degree, so a lower order's coefficients are
exactly the leading coefficients of a higher one and the padding is zeros.
The shader then evaluates one fixed-width polynomial with no branch, and the
padded terms contribute nothing.

Sources:
  analysis/derive_material_matrices.py  - the untinted colour transfer
  analysis/derive_tint_law.py           - `.tint()`, both variants
"""

import argparse
import itertools
import json
from pathlib import Path

BANNER = """// GENERATED by analysis/generate_material_law_header.py - do not edit.
//
// Apple's Liquid Glass material, measured on macOS 26.6.1 (25G76).
//
// UNTINTED.  A polynomial on the blurred backdrop, in sRGB CODE space.  An
// affine 3x3 is not enough - `regular`'s gray response bows above the chord by
// up to 4.4 code values at mid-scale - and the polynomial beats it on held-out
// backgrounds everywhere, 3.65 to 1.58 code values rms for `regular` in light.
// It also retires an unexplained constant: the x**0.795 space the shader used
// to carry was an artefact of a sparse sixteen-background fit, and refitting
// the same model on the colour lattice returns 1.195.
//
// Code space rather than linear light is measured, not assumed: the same
// polynomial fitted on linearised inputs and outputs is three to fifteen times
// worse held out, at every order tried.
//
// TINTED.  The tint composites over the material's OWN OUTPUT, not over the raw
// backdrop, and separates into luminance and chroma:
//
//     out = base(tint) + beta(tint) * lumaOf(substrate)
//                      + gamma(tint) * chromaOf(substrate)
//
// gamma is measured as either one or zero and nothing between - even a tint
// 0.645 code values off the gray axis already blocks the backdrop's colour
// completely, and only an EXACTLY gray one lets it through.  That is a colour
// SPACE distinction, not a threshold: an exactly gray sRGB colour resolves to a
// grayscale space and takes the other path.
//
// `.interactive(true)` carries no law because it has no effect: over sixteen
// backgrounds, both variants and both appearances, a static element renders
// byte-identically with and without it (analysis/measure_interactive_modifier.py).
"""


def exponents(order: int) -> list[tuple[int, int, int]]:
    """Trivariate exponent triples up to `order`, by total degree then value."""
    return [
        triple
        for triple in sorted(itertools.product(range(order + 1), repeat=3),
                             key=lambda t: (sum(t), t))
        if sum(triple) <= order
    ]


def product(triple: tuple[int, int, int], variable: str) -> str:
    factors = [f"{variable}.{axis}"
               for axis, power in zip("rgb", triple)
               for _ in range(power)]
    return " * ".join(factors) if factors else "1.0"


def emit_basis(name: str, triples: list[tuple[int, int, int]]) -> list[str]:
    lines = [f"void {name}(float3 unit, out float terms[{len(triples)}])",
             "{"]
    lines += [f"    terms[{index}] = {product(triple, 'unit')};"
              for index, triple in enumerate(triples)]
    lines.append("}\n")
    return lines


def emit_material(records) -> list[str]:
    order = max(record["order"] for record in records)
    triples = exponents(order)
    lines = [
        f"// Order {order} in the backdrop, {len(triples)} terms, evaluated by",
        "// walleTransferBasis below; each term carries its contribution to",
        "// (R, G, B) out.  Terms above a material's own chosen order are zero.",
        f"static const int kTransferTermCount = {len(triples)};\n",
        "struct WalleMaterialTransfer\n{",
        f"    float3 terms[{len(triples)}];",
        "};\n",
        *emit_basis("walleTransferBasis", triples),
    ]
    for record in records:
        name = (f"kMaterial{record['variant'].capitalize()}"
                f"{record['appearance'].capitalize()}")
        lines.append(f"// {record['variant']} / {record['appearance']}: "
                     f"{record['backgroundCount']} unclipped backgrounds, order "
                     f"{record['order']}, "
                     f"{record['rootMeanSquareResidualCodes']} rms / "
                     f"{record['maximumResidualCodes']} max code values, "
                     f"{record['heldOutRootMeanSquareCodes']} rms held out.")
        lines.append(f"static const WalleMaterialTransfer {name} = {{")
        lines.append("    {")
        coefficients = record["coefficients"]
        for index in range(len(triples)):
            row = (coefficients[index] if index < len(coefficients)
                   else [0.0, 0.0, 0.0])
            lines.append("        float3("
                         + ", ".join(f"{v: .8f}" for v in row) + "),")
        lines.append("    },")
        lines.append("};\n")
    return lines


def emit_tint(report) -> list[str]:
    entries = [
        (variant, appearance, entry)
        for variant, appearances in sorted(report["variants"].items())
        for appearance, entry in sorted(appearances.items())
        if entry.get("regimes", {}).get("chromatic") is not None
    ]
    order = max(entry["regimes"]["chromatic"]["order"]
                for _, _, entry in entries)
    triples = exponents(order)
    width = len(triples)
    neutral_order = max(
        (entry["regimes"]["neutral"]["order"]
         for _, _, entry in entries if entry["regimes"].get("neutral")),
        default=2)
    neutral_width = neutral_order + 1
    lines = [
        f"// Chromatic tints: order {order} in the tint, {width} terms, in the",
        "// same total-degree order as the transfer's basis.  Neutral tints are",
        f"// one-dimensional: order {neutral_order} in the tint's single level,"
        f" {neutral_width} terms.",
        "// Both bases run from the constant term upwards.  Each channel's base",
        "// coefficients are followed by its beta and then its gamma.",
        "//",
        "// gamma - how much of the substrate's own chroma survives - is a",
        "// fitted function of the tint wherever that beat pinning it.  Where",
        "// pinning won, the pinned value is written into the CONSTANT term of",
        "// the basis rather than branched on, so the shader has one path.",
        f"static const int kTintChromaticTermCount = {width};",
        f"static const int kTintNeutralTermCount = {neutral_width};\n",
        "struct WalleTintRegime\n{",
        f"    float chromaticBase[{3 * width}];",
        f"    float chromaticBeta[{3 * width}];",
        f"    float chromaticGamma[{3 * width}];",
        f"    float neutralBase[{3 * neutral_width}];",
        f"    float neutralBeta[{3 * neutral_width}];",
        f"    float neutralGamma[{3 * neutral_width}];",
        "};\n",
        *emit_basis("walleTintBasis", triples),
        f"void walleTintNeutralBasis(float level,"
        f" out float terms[{neutral_width}])",
        "{",
        *[f"    terms[{power}] = "
          + (" * ".join(["level"] * power) if power else "1.0") + ";"
          for power in range(neutral_width)],
        "}\n",
    ]
    for variant, appearance, entry in entries:
        regimes = entry["regimes"]
        chromatic, neutral = regimes["chromatic"], regimes.get("neutral")
        name = f"kTint{variant.capitalize()}{appearance.capitalize()}"
        lines.append(
            f"// {variant} / {appearance}: {chromatic['tintCount']} chromatic"
            f" at order {chromatic['order']}"
            + (" with fitted gamma" if chromatic["gammaFitted"] else "")
            + (f", {neutral['tintCount']} neutral"
               + (" with fitted gamma" if neutral["gammaFitted"] else "")
               if neutral else
               ", NEUTRAL NOT CAPTURED - the chromatic law stands in")
            + f"; fit {entry['rootMeanSquareResidualCodes']} rms /"
            f" {entry['maximumResidualCodes']} max code values,"
            f" {entry['heldOutRootMeanSquareCodes']} rms held out.")
        lines.append(f"static const WalleTintRegime {name} = {{")
        # Each regime's own width, so a lower-order fit is read from the front
        # of its rows and padded to the emitted width with zeros.  The pinned
        # gamma has no fitted row at all: it is the pinned value on the basis's
        # constant term, which sits first for the chromatic basis and last for
        # the neutral one.
        own = chromatic["termCount"]
        blocks = [(chromatic, slice(0, own), width, None),
                  (chromatic, slice(own, 2 * own), width, None)]
        blocks.append((chromatic, slice(2 * own, 3 * own), width, None)
                      if chromatic["gammaFitted"] else (None, None, width, 0.0))
        mine = neutral["termCount"] if neutral else neutral_width
        blocks += [(neutral, slice(0, mine), neutral_width, None),
                   (neutral, slice(mine, 2 * mine), neutral_width, None)]
        if neutral is None:
            blocks.append((None, None, neutral_width, 0.0))
        elif neutral["gammaFitted"]:
            blocks.append(
                (neutral, slice(2 * mine, 3 * mine), neutral_width, None))
        else:
            blocks.append((None, None, neutral_width, 1.0))
        for source, span, pad, pinned in blocks:
            lines.append("    {")
            for channel in range(3):
                if source is None:
                    # Both bases start at the constant term, so a pinned
                    # function is that value there and zeros after it.
                    row = [pinned] + [0.0] * (pad - 1)
                else:
                    row = list(source["coefficients"][channel][span])
                    row += [0.0] * (pad - len(row))
                lines.append("        "
                             + ", ".join(f"{v: .8f}" for v in row) + ",")
            lines.append("    },")
        lines.append("};\n")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--material", type=Path, required=True)
    parser.add_argument("--tint", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    arguments = parser.parse_args()

    material = json.loads(arguments.material.read_text(encoding="utf-8"))
    tint = json.loads(arguments.tint.read_text(encoding="utf-8"))
    lines = [BANNER, *emit_material(material["records"]), *emit_tint(tint)]
    arguments.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {arguments.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
